# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5dcb60d396ce4aba9e7c16ed553fb0931b447d2581756f1106a8e816e3835c7a3d3f9ee93b192e3cc2d867fde6eb2008419196b726edb20e73f0e448b8fea7

test:
  secret_key_base: cd7c99779ff7c7098ba462e22046ceccbdef8ce5936999df8aad7ede17a42f2e233c55cb8704399a2b6a48140bd936d864d81170974c82d2d2e5b1fa8c8e8ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
